---
- hosts: all
  become: True
  ignore_errors: 1
  gather_facts: no
  #become_user: root

  tasks:
     - name: Create a file
       file:
        path: /tmp/playbookfile
        mode: '0755'
        state: touch
       tags:
          - file
     - name: check something
       command: jahgwjfbfgg
       tags:
          - cmd
       

     - name: Create a directory
       file:
        path: /tmp/dir
        mode: '0700'
        state: directory
       tags:
          - name
     - name: Create a group
       group:
        name: security
        state: present


     - name: Create a user
       user:
         comment: Serge Admin
         shell: /bin/bash
         group: security
         name: serge
       when: ansible_os_family == "Iphone" or ansible_processor_nproc > 2

     - name: Check uptime
       command: uptime
     - name: Check the date
       shell: cat /etc/passwd | grep serge

