---
- name: Install apache
  yum:
    name: "{{ apache_pkg }}"
    state: "{{ pkg_state }}"

- name: Start Daemon
  service:
    name: "{{ service_name }}"
    state: "{{ service_state }}"

- name: Create file
  file:
    path: "{{ file_path }}"
    state: "{{ file_state }}"

- name: File content
  lineinfile:
    path: "{{ file_path }}"
    line: "{{ content }}"
